apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: graylog
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: graylog
    spec:
      containers:
      - env:
        - name: GRAYLOG_WEB_ENDPOINT_URI
          value: http://127.0.0.1:9000/api
        - name: GRAYLOG_PASSWORD_SECRET
          value: somepasswordpepper
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: 415e8a6ba1c3eb93e81df34731acc3d60efee685c8e6f7412592a45ba3a0e3b0
        image: graylog2/server:2.2.1-1
        name: graylog
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
